### ISSUE TITLE
not being able to start a training session.

### ISSUE THREAD

**Issue by userillumos** [Ehteshamciitwah/MSFR#1]
I am trying to train MSFR on my own dataset. But every time I run with "sh mvtec_run.sh" as mentioned in README file the code seems to be running in a test mode and it quickly ends. 
[DATASET_mvtec_METHOD_MSFR_RNG_SEED_54.log](https://github.com/user-attachments/files/17691872/DATASET_mvtec_METHOD_MSFR_RNG_SEED_54.log)
Sincerely hope I could get any help from you.

**Comment by HExin02** [comment]
how did you fix this problem？I meet that too...
